const swaggerJsdoc = require("swagger-jsdoc");

//import something from "./api/reviews";
// const options = {
//   swaggerDefinition: {
//     // Like the one described here: https://swagger.io/specification/#infoObject
//     info: {
//       version: "1.0.0",
//       title: "APIs Document",
//       description: "your description here",
//       termsOfService: "",
//       contact: {
//         name: "Sharukh",
//         email: "sdsharukh9@gmail.com",
//       },
//     },
//     // List of files to be processes. You can also set globs './routes/*.js'
//     apis: ["./api/*.js"],
//   },
// };

const options = {
  swaggerDefinition: {
    // Like the one described here: https://swagger.io/specification/#infoObject
    info: {
      title: "Bhalu API",
      version: "1.0.0",
      description: "Bhalu API with autogenerated swagger documentation",
      termsOfService: "",
      contact: {
        name: "Sharukh",
        email: "sdsharukh9@gmail.com",
      },
    },
  },
  // List of files to be processes. You can also set globs './routes/*.js'
  apis: ["./api/*.js"],
};

exports.swaggerDocument = options;
